import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { supabase } from './supabase';
import './styles.css';

type Role='player'|'staff';
type Approval='pending'|'approved'|'rejected';
type Profile={id:string;role:Role;full_name:string;school_grade:number|null;position:string|null;jersey_number:number|null;height_cm:number|null;weight_kg:number|null;dominant_foot:string|null;origin_team:string|null};
type ApprovalRow={user_id:string;status:Approval;rejection_reason:string|null};
type CaseRow={case_id:string;player_id:string;full_name:string;school_grade:number|null;position:string|null;injury_name:string;body_part:string;side:string|null;current_status:string;injury_date:string;updated_at:string;latest_rtp_status:string|null;open_tasks:number};
type ReportRow={id:number;player_id:string;injury_date:string;symptom:string;body_part:string;side:string|null;review_status:string;created_at:string};

type Screen='players'|'reports'|'team'|'case'|'admin';

const statusLabel:Record<string,string>={needs_attention:'要対応',rehab:'リハビリ中',observation:'経過観察',available:'参加可'};
const statusClass:Record<string,string>={needs_attention:'danger',rehab:'info',observation:'warn',available:'ok'};

function App(){
 const [session,setSession]=useState<any>(null),[profile,setProfile]=useState<Profile|null>(null),[approval,setApproval]=useState<ApprovalRow|null>(null),[isAdmin,setIsAdmin]=useState(false),[screen,setScreen]=useState<Screen>('players'),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session); setLoading(false)}); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{ if(!session){setProfile(null);setApproval(null);setIsAdmin(false);return;} loadIdentity(); },[session?.user?.id]);
 async function loadIdentity(){ setLoading(true); setError(''); const uid=session.user.id; const [{data:p,error:pe},{data:a,error:ae},{data:ad,error:ade}]=await Promise.all([
   supabase.from('profiles').select('id,role,full_name,school_grade,position,jersey_number,height_cm,weight_kg,dominant_foot,origin_team').eq('id',uid).maybeSingle(),
   supabase.from('account_approvals').select('user_id,status,rejection_reason').eq('user_id',uid).maybeSingle(),
   supabase.from('app_admins').select('user_id').eq('user_id',uid).maybeSingle()
 ]); if(pe||ae){setError((pe||ae)?.message||'読み込みエラー');} setProfile(p as any); setApproval(a as any); setIsAdmin(!!ad&&!ade); setLoading(false); }
 if(loading) return <Center>読み込み中...</Center>;
 if(!session) return <Auth />;
 if(approval?.status!=='approved') return <Pending status={approval?.status} reason={approval?.rejection_reason} onLogout={()=>supabase.auth.signOut()} />;
 return <Shell profile={profile} isAdmin={isAdmin} screen={screen} setScreen={setScreen} onLogout={()=>supabase.auth.signOut()}>{error&&<div className="error">{error}</div>}{screen==='players'&&<Players/>}{screen==='reports'&&<Reports profile={profile}/>} {screen==='team'&&<Team/>}{screen==='admin'&&isAdmin&&<Admin/>}{screen==='case'&&<Cases/>}</Shell>
}

function Auth(){const [mode,setMode]=useState<'login'|'signup'>('login'),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''); const [form,setForm]=useState<any>({email:'',password:'',password2:'',role:'player',full_name:'',school_grade:'1',position:'FW',height_cm:'',weight_kg:'',dominant_foot:'right',origin_team:''});
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setMsg(''); if(mode==='signup'&&form.password!==form.password2){setMsg('パスワードが一致しません');setBusy(false);return} if(!/^(?=.*[A-Za-z])(?=.*\d).{8,}$/.test(form.password)){setMsg('パスワードは8文字以上、英字と数字を含めてください');setBusy(false);return}
 if(mode==='login'){const {error}=await supabase.auth.signInWithPassword({email:form.email,password:form.password}); if(error)setMsg(error.message)} else {const metadata:any={role:form.role,full_name:form.full_name}; if(form.role==='player')Object.assign(metadata,{school_grade:Number(form.school_grade),position:form.position,height_cm:Number(form.height_cm),weight_kg:Number(form.weight_kg),dominant_foot:form.dominant_foot,origin_team:form.origin_team}); const {error}=await supabase.auth.signUp({email:form.email,password:form.password,options:{data:metadata}}); setMsg(error?error.message:'登録しました。管理者の承認後に利用できます。');} setBusy(false)};
 return <div className="authPage"><div className="authCard"><div className="brandBig">KTRS MED</div><div className="sub">FIELD MEDICAL HUB</div><h2>{mode==='login'?'ログイン':'アカウント新規作成'}</h2><form onSubmit={submit} className="form"><input placeholder="メールアドレス" type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder="パスワード" type="password" required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>{mode==='signup'&&<><input placeholder="パスワード（確認）" type="password" required value={form.password2} onChange={e=>setForm({...form,password2:e.target.value})}/><input placeholder="氏名" required value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="player">選手</option><option value="staff">スタッフ</option></select>{form.role==='player'&&<div className="grid2"><select value={form.school_grade} onChange={e=>setForm({...form,school_grade:e.target.value})}><option>1</option><option>2</option><option>3</option></select><select value={form.position} onChange={e=>setForm({...form,position:e.target.value})}><option>GK</option><option>DF</option><option>MF</option><option>FW</option></select><input placeholder="身長 cm" type="number" required value={form.height_cm} onChange={e=>setForm({...form,height_cm:e.target.value})}/><input placeholder="体重 kg" type="number" required value={form.weight_kg} onChange={e=>setForm({...form,weight_kg:e.target.value})}/><select value={form.dominant_foot} onChange={e=>setForm({...form,dominant_foot:e.target.value})}><option value="right">右</option><option value="left">左</option><option value="both">両方</option></select><input placeholder="出身チーム" value={form.origin_team} onChange={e=>setForm({...form,origin_team:e.target.value})}/></div>}</>}
 <button disabled={busy}>{busy?'処理中...':mode==='login'?'ログイン':'登録する'}</button></form>{msg&&<div className="notice">{msg}</div>}<button className="linkBtn" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'アカウントの新規作成':'ログインへ戻る'}</button><p className="fine">医療機関の診断に代わるものではありません。</p></div></div>}

function Pending({status,reason,onLogout}:{status?:Approval;reason?:string|null;onLogout:()=>void}){return <Center><div className="authCard"><h2>{status==='rejected'?'アカウントは承認されていません':'管理者の承認待ちです'}</h2><p>{status==='rejected'?(reason||'管理者にお問い合わせください。'):'承認後にKTRS MEDを利用できます。'}</p><button onClick={onLogout}>ログアウト</button></div></Center>}
function Shell({profile,isAdmin,screen,setScreen,onLogout,children}:any){return <><header><div><b>KTRS MED</b><span> FIELD MEDICAL HUB</span></div><nav>{[['players','選手一覧'],['reports','選手報告'],['team','チーム状況'],['case','記録・判断']].map(([k,l])=><button key={k} className={screen===k?'active':''} onClick={()=>setScreen(k)}>{l}</button>)}{isAdmin&&<button className={screen==='admin'?'active':''} onClick={()=>setScreen('admin')}>管理</button>}</nav><div className="user">{profile?.full_name||''}<button onClick={onLogout}>ログアウト</button></div></header><main>{children}</main><footer>© K-TRAINERS. All rights reserved.<br/><span>傷害情報は認証されたサーバーに保存されます。</span></footer></>}

function Players(){const [rows,setRows]=useState<CaseRow[]>([]),[q,setQ]=useState(''),[loading,setLoading]=useState(true); useEffect(()=>{load()},[]); async function load(){const {data}=await supabase.from('active_case_board').select('*').order('updated_at',{ascending:false}); setRows((data||[]) as any);setLoading(false)}; const filtered=useMemo(()=>rows.filter(r=>r.full_name.includes(q)||r.injury_name.includes(q)),[rows,q]); return <section><Title t="選手一覧" s="高校年代サッカー｜メディカル管理"/><div className="cards"><Stat n={rows.filter(r=>r.current_status==='needs_attention').length} l="要対応" c="danger"/><Stat n={rows.filter(r=>r.current_status==='rehab').length} l="リハビリ中" c="info"/><Stat n={rows.filter(r=>r.current_status==='observation').length} l="経過観察" c="warn"/></div><div className="toolbar"><input placeholder="選手名・傷害名で検索" value={q} onChange={e=>setQ(e.target.value)}/></div>{loading?<p>読み込み中...</p>:<div className="tableWrap"><table><thead><tr><th>氏名</th><th>学年/Pos</th><th>傷害</th><th>状態</th><th>更新</th></tr></thead><tbody>{filtered.map(r=><tr key={r.case_id}><td><b>{r.full_name}</b></td><td>{r.school_grade||'-'}年 / {r.position||'-'}</td><td>{r.injury_name}<small>{r.injury_date}・{r.body_part}</small></td><td><span className={'pill '+statusClass[r.current_status]}>{statusLabel[r.current_status]||r.current_status}</span></td><td>{new Date(r.updated_at).toLocaleDateString('ja-JP')}</td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">現在、進行中の傷害ケースはありません。</div>}</div>}</section>}

function Reports({profile}:{profile:Profile|null}){const [rows,setRows]=useState<ReportRow[]>([]),[form,setForm]=useState<any>({injury_date:'',symptom:'',body_part:'',side:'right'}),[msg,setMsg]=useState(''); const staff=profile?.role==='staff'; useEffect(()=>{load()},[]); async function load(){const {data}=await supabase.from('injury_reports').select('id,player_id,injury_date,symptom,body_part,side,review_status,created_at').order('created_at',{ascending:false});setRows((data||[]) as any)} async function submit(e:any){e.preventDefault();if(!profile)return;const {error}=await supabase.from('injury_reports').insert({player_id:profile.id,injury_date:form.injury_date,symptom:form.symptom,body_part:form.body_part,side:form.side,hospital_status:'未受診',review_status:'pending'});setMsg(error?error.message:'報告を送信しました');if(!error){setForm({injury_date:'',symptom:'',body_part:'',side:'right'});load()}} async function convert(id:number){const {error}=await supabase.rpc('staff_convert_report_to_case',{report_id:id});setMsg(error?error.message:'正式な傷害ケースに変換しました');load()}
 return <section><Title t="選手報告" s="選手自己申告 → スタッフ確認"/>{profile?.role==='player'&&<form className="panel form" onSubmit={submit}><h3>新しい傷害・症状を報告</h3><div className="grid2"><input type="date" required value={form.injury_date} onChange={e=>setForm({...form,injury_date:e.target.value})}/><select value={form.side} onChange={e=>setForm({...form,side:e.target.value})}><option value="right">右</option><option value="left">左</option><option value="both">両側</option><option value="none">左右なし</option></select><input placeholder="傷害名または症状" required value={form.symptom} onChange={e=>setForm({...form,symptom:e.target.value})}/><input placeholder="受傷部位" required value={form.body_part} onChange={e=>setForm({...form,body_part:e.target.value})}/></div><button>報告する</button></form>}{msg&&<div className="notice">{msg}</div>}<div className="tableWrap"><table><thead><tr><th>日付</th><th>症状</th><th>部位</th><th>状態</th>{staff&&<th></th>}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.injury_date}</td><td>{r.symptom}</td><td>{r.body_part}</td><td>{r.review_status==='pending'?'未確認':'確認済み'}</td>{staff&&<td>{r.review_status==='pending'&&<button onClick={()=>convert(r.id)}>傷害ケース化</button>}</td>}</tr>)}</tbody></table></div></section>}

function Team(){const [d,setD]=useState<any>(null);useEffect(()=>{supabase.from('staff_dashboard_summary').select('*').maybeSingle().then(({data})=>setD(data))},[]);return <section><Title t="チーム状況" s="本日のメディカル状況"/><div className="cards"><Stat n={d?.pending_reports||0} l="未確認報告" c="warn"/><Stat n={d?.needs_attention_cases||0} l="要対応" c="danger"/><Stat n={d?.rehab_cases||0} l="リハビリ" c="info"/><Stat n={d?.unavailable_today||0} l="参加不可" c="danger"/><Stat n={d?.modified_today||0} l="制限あり" c="warn"/><Stat n={d?.due_tasks||0} l="期限ToDo" c="info"/></div></section>}
function Cases(){const [rows,setRows]=useState<CaseRow[]>([]);useEffect(()=>{supabase.from('active_case_board').select('*').order('updated_at',{ascending:false}).then(({data})=>setRows((data||[]) as any))},[]);return <section><Title t="記録・判断支援" s="評価・対応・リハビリ・復帰判断"/><div className="caseGrid">{rows.map(r=><div className="panel" key={r.case_id}><h3>{r.full_name}</h3><p><b>{r.injury_name}</b> / {r.body_part}</p><span className={'pill '+statusClass[r.current_status]}>{statusLabel[r.current_status]||r.current_status}</span><p className="muted">未完了ToDo: {r.open_tasks}件</p></div>)}</div></section>}
function Admin(){const [rows,setRows]=useState<any[]>([]),[msg,setMsg]=useState('');useEffect(()=>{load()},[]);async function load(){const {data,error}=await supabase.rpc('admin_list_accounts',{filter_status:null});if(!error)setRows(data||[])}async function act(id:string,status:'approved'|'rejected'){const {error}=await supabase.rpc('admin_set_account_approval',{target_user_id:id,new_status:status,reason:status==='rejected'?'管理者により却下':''});setMsg(error?error.message:'更新しました');load()}return <section><Title t="アカウント承認" s="管理者専用"/>{msg&&<div className="notice">{msg}</div>}<div className="tableWrap"><table><thead><tr><th>氏名</th><th>区分</th><th>学年/Pos</th><th>状態</th><th>操作</th></tr></thead><tbody>{rows.map(r=><tr key={r.user_id}><td>{r.full_name}</td><td>{r.role==='player'?'選手':'スタッフ'}</td><td>{r.school_grade?`${r.school_grade}年 / ${r.player_position||'-'}`:'-'}</td><td>{r.status}</td><td>{r.status==='pending'&&<><button onClick={()=>act(r.user_id,'approved')}>承認</button> <button className="secondary" onClick={()=>act(r.user_id,'rejected')}>却下</button></>}</td></tr>)}</tbody></table></div></section>}
function Title({t,s}:{t:string;s:string}){return <div className="title"><h1>{t}</h1><p>{s}</p></div>}
function Stat({n,l,c}:{n:number;l:string;c:string}){return <div className={'stat '+c}><b>{n}</b><span>{l}</span></div>}
function Center({children}:{children:React.ReactNode}){return <div className="center">{children}</div>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);